name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10.17
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.17

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install flake8 pytest

    - name: Run flake8 linter
      run: |
        flake8 .

    - name: Run tests with pytest
      run: |
        pytest test_ml.py
